/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutoriaisRouteImport } from './routes/tutoriais'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AnalisarRouteImport } from './routes/analisar'
import { Route as IndexRouteImport } from './routes/index'

const TutoriaisRoute = TutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisarRoute = AnalisarRouteImport.update({
  id: '/analisar',
  path: '/analisar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisar': typeof AnalisarRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/tutoriais': typeof TutoriaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisar': typeof AnalisarRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/tutoriais': typeof TutoriaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisar': typeof AnalisarRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/tutoriais': typeof TutoriaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analisar' | '/conta' | '/contato' | '/tutoriais'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analisar' | '/conta' | '/contato' | '/tutoriais'
  id: '__root__' | '/' | '/analisar' | '/conta' | '/contato' | '/tutoriais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisarRoute: typeof AnalisarRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  TutoriaisRoute: typeof TutoriaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutoriais': {
      id: '/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof TutoriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisar': {
      id: '/analisar'
      path: '/analisar'
      fullPath: '/analisar'
      preLoaderRoute: typeof AnalisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisarRoute: AnalisarRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  TutoriaisRoute: TutoriaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
